In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis

Loading Iris dataset

In [5]:
df, target = load_iris(return_X_y=True)
df = pd.DataFrame(df, columns=["sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)	"])
df["label"] = target
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)\t,label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


Train-test split and mode evaluation function

In [92]:
x, y = load_iris(return_X_y=True)
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.5, random_state=0)


def evaluate_model(model_func, model_name, x_train=X_train, x_test=X_test, y_train=Y_train, y_test=Y_test):
    #gnb = GaussianNB()
    model = model_func()
    y_pred1 = model.fit(x_train, y_train).predict(x_test)

    x_train, x_test = x_test, x_train
    y_train, y_test = y_test, y_train
    #gnb = GaussianNB()
    model = model_func()
    y_pred2 = model.fit(x_train, y_train).predict(x_test)

    y_pred = np.round(np.append(y_pred2, y_pred1))
    y_true = np.append(y_test, y_train)
    print(f"Evaluating {model_name} model")
    print(f"Accuracy: {round((y_pred == y_true).sum() / len(y), 4)}")
    print(f"Confusion Matrix:\n {confusion_matrix(y_true, y_pred, labels=[0, 1, 2])}")

Naïve Baysian

In [94]:
evaluate_model(lambda : GaussianNB(), "Naïve Baysian")

Evaluating Naïve Baysian model
Accuracy: 0.96
Confusion Matrix:
 [[50  0  0]
 [ 0 48  2]
 [ 0  4 46]]


Linear Regression

In [77]:
evaluate_model(lambda : LinearRegression(), "Linear Regression")

Evaluating Linear Regression model
Accuracy: 0.9667
Confusion Matrix:
 [[50  0  0]
 [ 0 47  3]
 [ 0  2 48]]


Polynomial of degree 2 regression

In [83]:
poly = PolynomialFeatures(2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)
evaluate_model(lambda : LinearRegression(), "Polynomial of degree 2 regression",
               x_train=X_train_poly, x_test=X_test_poly)

Evaluating Polynomial of degree 2 regression model
Accuracy: 0.94
Confusion Matrix:
 [[49  1  0]
 [ 0 47  3]
 [ 0  3 45]]


Polynomial of degree 3 regression

In [86]:
poly = PolynomialFeatures(3)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)
evaluate_model(lambda : LinearRegression(), "Polynomial of degree 3 regression",
               x_train=X_train_poly, x_test=X_test_poly)

Evaluating Polynomial of degree 3 regression model
Accuracy: 0.82
Confusion Matrix:
 [[43  3  1]
 [ 3 44  3]
 [ 0  5 36]]


KNN Classifier

In [87]:
evaluate_model(lambda : KNeighborsClassifier(n_neighbors=3), "KNN Classifier")

Evaluating KNN Classifier model
Accuracy: 0.96
Confusion Matrix:
 [[50  0  0]
 [ 0 48  2]
 [ 0  4 46]]


Linear Discriminant Analysis

In [89]:
evaluate_model(lambda : LinearDiscriminantAnalysis(), "Linear Discriminant Analysis")

Evaluating Linear Discriminant Analysis model
Accuracy: 0.9667
Confusion Matrix:
 [[50  0  0]
 [ 0 47  3]
 [ 0  2 48]]


Quadratic Discriminant Analysis

In [91]:
evaluate_model(lambda : QuadraticDiscriminantAnalysis(), "Quadratic Discriminant Analysis")

Evaluating Quadratic Discriminant Analysis model
Accuracy: 0.96
Confusion Matrix:
 [[50  0  0]
 [ 0 46  4]
 [ 0  2 48]]
