In [3]:
import pandas as pd
import numpy as np
import random


In [11]:
print("Part 1: Policy Iteration RL Algorithm")
gamma = 1
rewardSize = -1
gridSize = 5
terminationStates = [[0,0], [gridSize-1, gridSize-1]]
actions = [[-1, 0], [1, 0], [0, 1], [0, -1]]
numIterations = 1000

def actionRewardFunction(initialPosition, action):
    
    if initialPosition in terminationStates:
        return initialPosition, 0
    
    reward = rewardSize
    finalPosition = np.array(initialPosition) + np.array(action)
    if -1 in finalPosition or gridSize in finalPosition: 
        finalPosition = initialPosition
        
    return finalPosition, reward



Part 1: Policy Iteration RL Algorithm


In [9]:
# Initialization
valueMap = np.zeros((gridSize, gridSize))
states = [[i, j] for i in range(gridSize) for j in range(gridSize)]
# values of the value function at step 0
valueMap

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# policy evaluation
deltas = []
for it in range(numIterations):
    copyValueMap = np.copy(valueMap)
    deltaState = []
    for state in states:
        weightedRewards = 0
        for action in actions:
            finalPosition, reward = actionRewardFunction(state, action)
            weightedRewards += (1/len(actions))*(reward+(gamma*valueMap[finalPosition[0], finalPosition[1]]))
        deltaState.append(np.abs(copyValueMap[state[0], state[1]]-weightedRewards))
        copyValueMap[state[0], state[1]] = weightedRewards
    deltas.append(deltaState)
    valueMap = copyValueMap
    if it in [0,1,2,9, 99, numIterations-1]:
        print("Iteration {}".format(it+1))
        print(valueMap)
        print("")

Iteration 1
[[ 0. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  0.]]

Iteration 2
[[ 0.   -1.75 -2.   -2.   -2.  ]
 [-1.75 -2.   -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -2.   -1.75]
 [-2.   -2.   -2.   -1.75  0.  ]]

Iteration 3
[[ 0.     -2.4375 -2.9375 -3.     -3.    ]
 [-2.4375 -2.875  -3.     -3.     -3.    ]
 [-2.9375 -3.     -3.     -3.     -2.9375]
 [-3.     -3.     -3.     -2.875  -2.4375]
 [-3.     -3.     -2.9375 -2.4375  0.    ]]

Iteration 10
[[ 0.         -6.27515411 -8.66638184 -9.50043869 -9.72789001]
 [-6.27515411 -8.0535965  -9.10924911 -9.47802734 -9.50043869]
 [-8.66638184 -9.10924911 -9.3196106  -9.10924911 -8.66638184]
 [-9.50043869 -9.47802734 -9.10924911 -8.0535965  -6.27515411]
 [-9.72789001 -9.50043869 -8.66638184 -6.27515411  0.        ]]

Iteration 100
[[  0.         -21.71170525 -32.35492757 -37.33944143 -39.20100637]
 [-21.71170525 -28.92485138 -34.23579213 -36.723715