In [3]:
import pandas as pd
import numpy as np
import random


In [37]:
print("Part 1: Policy Iteration RL Algorithm")
gamma = 1
rewardSize = -1
gridSize = 5
terminationStates = [[0,0], [gridSize-1, gridSize-1]]
actions = [[-1, 0], [1, 0], [0, 1], [0, -1]]
numIterations = 1000

def actionRewardFunction(initialPosition, action):
    
    if initialPosition in terminationStates:
        return initialPosition, 0
    
    reward = rewardSize
    finalPosition = np.array(initialPosition) + np.array(action)
    if -1 in finalPosition or gridSize in finalPosition: 
        finalPosition = initialPosition
        
    return finalPosition, reward



Part 1: Policy Iteration RL Algorithm


In [38]:
# Initialization
valueMap = np.zeros((gridSize, gridSize))
states = [[i, j] for i in range(gridSize) for j in range(gridSize)]
# values of the value function at step 0
valueMap

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
# policy evaluation
deltas = []
sums = []
sum_pre = 0
thld = 0.05
for it in range(numIterations):
    copyValueMap = np.copy(valueMap)
    deltaState = []
    for state in states:
        weightedRewards = 0
        for action in actions:
            finalPosition, reward = actionRewardFunction(state, action)
            weightedRewards += (1/len(actions))*(reward+(gamma*valueMap[finalPosition[0], finalPosition[1]]))
        deltaState.append(np.abs(copyValueMap[state[0], state[1]]-weightedRewards))
        copyValueMap[state[0], state[1]] = weightedRewards
    deltas.append(deltaState)
    _sum = np.sum(copyValueMap)
    sums.append(_sum)
    valueMap = copyValueMap
    if it in [0, 9, numIterations - 1]:
        print("Iteration {}".format(it + 1))
        print(f"sum:{_sum}")
        print(valueMap)
        print("")
    # stop if sum diff is less than a pre-set threshold
    if abs((_sum - sum_pre) / sum_pre) < thld:
        print(f"Iteration {it + 1}. Sum delta smaller than threshold({thld}), stop.")
        print(f"sum:{_sum}")
        print(valueMap)
        print("")
        break
    sum_pre = _sum

Iteration 1
sum:-23.0
[[ 0. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  0.]]

Iteration 10
sum:-198.0435333251953
[[ 0.         -6.27515411 -8.66638184 -9.50043869 -9.72789001]
 [-6.27515411 -8.0535965  -9.10924911 -9.47802734 -9.50043869]
 [-8.66638184 -9.10924911 -9.3196106  -9.10924911 -8.66638184]
 [-9.50043869 -9.47802734 -9.10924911 -8.0535965  -6.27515411]
 [-9.72789001 -9.50043869 -8.66638184 -6.27515411  0.        ]]

Iteration 17. Sum delta smaller than threshold(0.05), stop.
sum:-305.65811491012573
[[  0.          -9.30829477 -13.30887728 -14.93846651 -15.46978791]
 [ -9.30829477 -12.15456855 -14.04201174 -14.81090012 -14.93846651]
 [-13.30887728 -14.04201174 -14.39700056 -14.04201174 -13.30887728]
 [-14.93846651 -14.81090012 -14.04201174 -12.15456855  -9.30829477]
 [-15.46978791 -14.93846651 -13.30887728  -9.30829477   0.        ]]



In [44]:
print("Part 2: Value Iteration RL Algorithm")

gamma = 1
rewardSize = -1
gridSize = 5
terminationStates = [[0,0], [gridSize-1, gridSize-1]]
actions = [[-1, 0], [1, 0], [0, 1], [0, -1]]
numIterations = 1000

# Initialization
valueMap = np.zeros((gridSize, gridSize))
states = [[i, j] for i in range(gridSize) for j in range(gridSize)]
# values of the value function at step 0

# value evaluation
deltas = []
sums = []
sum_pre = 0
thld = 0.05
for it in range(numIterations):
    copyValueMap = np.copy(valueMap)
    deltaState = []
    for state in states:
        weightedRewards = []
        for action in actions:
            finalPosition, reward = actionRewardFunction(state, action)
            #print(f"{reward}+{gamma}*{valueMap[finalPosition[0], finalPosition[1]]}")
            #_reward = (1/len(actions)) * (reward+(gamma*valueMap[finalPosition[0], finalPosition[1]]))
            _reward = reward + gamma * valueMap[finalPosition[0], finalPosition[1]]
            weightedRewards.append(_reward)
        best_reward = max(weightedRewards)
        #print(f"best_reward:{best_reward}")
        deltaState.append(np.abs(copyValueMap[state[0], state[1]] - best_reward))
        copyValueMap[state[0], state[1]] = best_reward
    deltas.append(deltaState)
    _sum = np.sum(copyValueMap)
    sums.append(_sum)
    valueMap = copyValueMap
    if it in [0, 1, 2, 9, numIterations - 1]:
        print("Iteration {}".format(it + 1))
        print(f"sum:{_sum}")
        print(valueMap)
        print("")
    # stop if sum diff is less than a pre-set threshold
    if abs((_sum - sum_pre) / sum_pre) < thld:
        print(f"Iteration {it + 1}. Sum delta smaller than threshold({thld}), stop.")
        print(f"sum:{_sum}")
        print(valueMap)
        print("")
        break
    sum_pre = _sum

Part 2: Value Iteration RL Algorithm
Iteration 1
sum:-23.0
[[ 0. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  0.]]

Iteration 2
sum:-42.0
[[ 0. -1. -2. -2. -2.]
 [-1. -2. -2. -2. -2.]
 [-2. -2. -2. -2. -2.]
 [-2. -2. -2. -2. -1.]
 [-2. -2. -2. -1.  0.]]

Iteration 3
sum:-55.0
[[ 0. -1. -2. -3. -3.]
 [-1. -2. -3. -3. -3.]
 [-2. -3. -3. -3. -2.]
 [-3. -3. -3. -2. -1.]
 [-3. -3. -2. -1.  0.]]

Iteration 5. Sum delta smaller than threshold(0.05), stop.
sum:-60.0
[[ 0. -1. -2. -3. -4.]
 [-1. -2. -3. -4. -3.]
 [-2. -3. -4. -3. -2.]
 [-3. -4. -3. -2. -1.]
 [-4. -3. -2. -1.  0.]]

